name: CI
on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build firmware
        run: make build
      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: firmware/

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download firmware
        uses: actions/download-artifact@v2
        with:
          name: firmware
          path: firmware/

      - name: Prepare for release
        run: |
          tar czf firmware.tgz firmware/
          ls -al

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          vsha=${{ github.sha }}
          version=$(echo $vsha | cut -b -5)
          date=$(date -Idate)
          echo $version

          gh release create "v1-$version" --latest --title "Release $version" --notes "New firmware version from $date. See flash instructions [on README.md](https://github.com/homebots/vm)" firmware.tgz

  flash:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download firmware
        uses: actions/download-artifact@v2
        with:
          name: firmware
          path: firmware/

      - name: Upload to ESP flash
        run: |
          set -e
          curl -sS -X POST ${{ secrets.ESP_LIVE_URL }}/prepare

          for i in $(ls firmware -1 | grep '0x'); do
            stat firmware/$i
            curl -sS ${{ secrets.ESP_LIVE_URL }}/upload/$i --data-binary @firmware/$i;
          done

          curl -sS -X POST ${{ secrets.ESP_LIVE_URL }}/flash
          curl -sS -X POST ${{ secrets.ESP_LIVE_URL }}/reset
          sleep 5
          curl -sS -X POST ${{ secrets.ESP_LIVE_URL }}/connect
