name: CI
on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build firmware
        run: make build
      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: firmware/
