name: CI
on:
  - push
  - workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build firmware
        run: make build
      - name: Upload firmware
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: firmware/

  release:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download firmware
        uses: actions/download-artifact@v2
        with:
          name: firmware
          path: firmware/

      - name: Prepare for release
        run: |
          vsha=${{ github.sha }}
          version=$(echo $vsha | cut -b -10)
          date=$(date -Idate)

          tar czf firmware.tgz firmware/
          ls -al

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create $version --title "Release $version" --notes "New firmware version from $date. See flash instructions [on README.md](https://github.com/homebots/vm)"
          gh release upload $version firmware.tgz --clobber

      - name: Publish firmware
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload $version firmware.tgz --clobber

      - name: Upload to ESP flash
        run: |
          curl ${{ secrets.ESP_LIVE_URL }}/prepare

          for i in $(ls firmware -1); do
            curl -sS ${{ secrets.ESP_LIVE_URL }}/upload/$i -d @firmware/$i;
          done

          curl ${{ secrets.ESP_LIVE_URL }}/flash
          curl ${{ secrets.ESP_LIVE_URL }}/run

  flash:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download firmware
        uses: actions/download-artifact@v2
        with:
          name: firmware
          path: firmware/

      - name: Upload to ESP flash
        run: |
          curl ${{ secrets.ESP_LIVE_URL }}/prepare

          for i in $(ls firmware -1); do
            curl -sS ${{ secrets.ESP_LIVE_URL }}/upload/$i -d @firmware/$i;
          done

          curl ${{ secrets.ESP_LIVE_URL }}/flash
          curl ${{ secrets.ESP_LIVE_URL }}/run
